import { Merriweather } from "next/font/google";
import "./globals.css";

const merriweather = Merriweather({ subsets: ["latin"], weight:['300','400', '700'] });

export const metadata = {
  title: "Cooking Recipe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={merriweather.className}>{children}</body>
    </html>
  );
}
